sudo: false
language: python
python: 3.8

# command to install dependencies
install:
  - pip install .
  - pip install pytest-cov

script:
  - pytest --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)

